development:
  secret_key_base: 87d84d462f466cf85fd16496761c9e294ee1ca8c938c7bd1e880bbff0722f2b17b49c81b8c79109c45d74f3ceeca4e7af73cec7c46293e9e820d1f0a58d12223
  stripe_private_key: sk_test_ZNKOiYqanJcUjRsSnNwwa4sC
  stripe_public_key: pk_test_TbhhQXRpBIZIsUqENobya4pF
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  slack_client: '146802301377.168447391220'
  slack_secret: 5a9e7990a7f58712db54faf788418e77

test:
  secret_key_base: 26a7a1175c5b9214076b80cb3bcff34131efaa3ec6cf1a1d9909eda4e1a520335c065c996e800eed683631df77c5e3c69021877e31d59ab879d5d1a3d68e19ef
  stripe_private_key: sk_test_ZNKOiYqanJcUjRsSnNwwa4sC
  stripe_public_key: pk_test_TbhhQXRpBIZIsUqENobya4pF
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  slack_client: '146802301377.168447391220'
  slack_secret: 5a9e7990a7f58712db54faf788418e77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_private_key: <%= ENV["STRIPE_PRIVATE_KEY"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  slack_client: <%= ENV['SLACK_CLIENT'] %>
  slack_secret: <%= ENV['SLACK_SECRET'] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_private_key: sk_test_ZNKOiYqanJcUjRsSnNwwa4sC
  stripe_public_key: pk_test_TbhhQXRpBIZIsUqENobya4pF
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  slack_client: '146802301377.177195557143'
  slack_secret: 48ab479302cbe27425913e2c4a6e039e
